version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile path
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:nimahotnew@db:5432/nima_db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nimahotnew
      - POSTGRES_DB=nima_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
